version: '3.8'

services:
  backend:
    image: multi_db_service
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    networks:
      - service_db_cache
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: demo_db_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    ports:
      - 3306:3306
    networks:
      - service_db_cache

  redis:
    image: redis:latest
    container_name: demo_redis_container
    ports:
      - 6379:6379
    networks:
      - service_db_cache
networks:
  service_db_cache: {}